server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/score_update?createDatabaseIfNotExist=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

score:
  api:
    url: http://static.cricinfo.com/rss/livescores.xml
